### PR TITLE
Use template in tasks to properly update configuration files

### PR DESCRIPTION
**Pull request by gab-arrobo**

### CODE REVIEW

**Comment by llpeterson** [comment]
Looks good to me, but maybe Bilal should weight in since he has more Ansible experience than me. (I wonder if you could set a variable, say `useransim_ip`, just once in the playbook, and then use it instead of reevaluating the "host_inventory expression" in the template.)

**Comment by gab-arrobo** [comment]
I did think about the variable (e.g., `ueransim_ip`) but I did not do it because it is a loop for all nodes in [ueransim_nodes] and that IP address changes depending on which (ueransim) node is executing it. Feel free to make any changes you deem appropriate

**Comment by gab-arrobo** [comment]
@llpeterson,
FYI, I tested the changes in this PR using 3 ueransim instances (servers)
```yaml
ueransim:
  servers:
    0:
      - "custom-gnb.yaml"
      - "custom-ue.yaml"
    1:
      - "custom-gnb-1.yaml"
      - "custom-ue-1.yaml"
    2:
      - "custom-gnb-2.yaml"
      - "custom-ue-2.yaml"

```

**Comment by llpeterson** [comment]
Ah. Good point.

**Pull request merged**
